name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    - name: Run build
      run: npm run build

  deploy:
    name: CD Pipeline
    needs: buildAndTest
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

    - name: Configure AWS_ACCESS_KEY_ID
      run: aws configure set aws_accesskey_id "$AWS_ACCESS_KEY_ID"
    - name: Configure AWS_SECRET_ACCESS_KEY
      run: aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - name: Configure AWS region
      run: aws configure set region eu-west-1
    - name: Build
      run: sh build.sh
    - name: Deploy
      run: sh deploy.sh